### PR TITLE
*: delete ebuilds needed by coreos-devel/sdk-extras

### PR DESCRIPTION
**Pull request by dongsupark**
Apparently the `coreos-devel/sdk-extras` was originally meant to work as a meta package to pull in all the optional packages in the SDK at once.
It has been unmaintained since 2~3 years, so an attempt of `emerge coreos-devel/sdk-extras` will give you a huge list of conflicts to resolve.
It is difficult to resurrect sdk-extras at the moment.
Delete `coreos-devel/sdk-extras` completely.
Doing that, we can delete more than 20 other packages from the source tree.

In this PR we delete:

* `app-admin/python-updater`
* `app-crypt/tpm-tools`
* `app-editors/emacs`
* `app-emacs/emacs-common-gentoo`
* `app-eselect/eselect-emacs`
* `app-eselect/eselect-ctags`
* `app-misc/screen`
* `app-misc/tmux`
* `app-portage/eix`
* `app-text/dos2unix`
* `app-text/tree`
* `dev-go/glide`
* `dev-go/godep`
* `dev-python/awscli`
* `dev-python/botocore`
* `dev-python/futures`
* `dev-python/jmespath`
* `dev-python/python-dateutil`
* `dev-python/s3transfer`
* `dev-util/cscope`
* `dev-util/ctags`
* `dev-util/valgrind`
* `net-libs/liblockfile`
* `sys-apps/ed`
* `sys-libs/libutempter`

This PR should be merged together with https://github.com/kinvolk/coreos-overlay/pull/1207 .

## Testing done

CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3331/cldsv

### CODE REVIEW

**Comment by dongsupark** [comment]
CI passed

**Comment by jepio** [comment]
Such a shame to see so many good packages disappear - I hope we can bring back something like it when we move to a full portage checkout one day.

The only one I question is nano - afaik nano is the default dependency for virtual/editor-0. I would keep at least nano around for people who are unfamiliar with vi.

**Review by jepio — APPROVED** [review]
OK except I would keep nano around.

**Comment by dongsupark** [comment]
All right. I brought back nano.
If there are other packages that should stay, please let me know.

Of course we can add some packages back in the future, if they are necessary.
Though someone should clean up stale ebuilds periodically.
Otherwise the code base will be full bloated.

**Review by krnowak — APPROVED** [review]
Nice, I like it. There are even some python packages dropped, so some work less for me. :)

**Pull request merged**
