### PR TITLE
dev-libs/libgcrypt: sync with ::gentoo

### PR DESCRIPTION
**Pull request by tormath1**
1.8.8 is not stable yet - accepted keywords has been updated in
::coreos-overlay.

Ref: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5ebb8899e39bc7a7773fe930e68697cc48aab8d3

Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>

:warning: to be merged with https://github.com/kinvolk/coreos-overlay/pull/1093

## Testing done

- jenkins (:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/2977/cldsv/

### CODE REVIEW

**Comment by jepio** [comment]
Looks good to me, but i'll take the chance to ask a couple of questions:
* do we always sync the whole folder or just the desired version?
* you upgraded to libgcrypt-1.8.8 but libgcrypt-1.9.3 is available. what's stopping us from updating to that?

**Review by jepio — APPROVED** [review]

**Review by sayanchowdhury — COMMENTED** [review]
Same thoughts as @jepio. Since 1.9.3 is available, it would be good to move to that.

**Comment by tormath1** [comment]
@sayanchowdhury @jepio thanks for reviewing ! Bumped to 1.9.3 in https://github.com/kinvolk/coreos-overlay/pull/1093. It builds locally and `packages-matrix` job is rebuilding.

> you upgraded to libgcrypt-1.8.8 but libgcrypt-1.9.3 is available. what's stopping us from updating to that?

nothing actually - I wanted to stay on track with 1.8.x releases and the CVE was fixed in 1.8.8 but yeah, I'll know for the next upgrades :rocket: 

> do we always sync the whole folder or just the desired version?

I personally remove the folder then copy the target one. This is basically what the `update_ebuilds` script [does](https://github.com/kinvolk/flatcar-scripts/blob/aa27b1d11f0cd39e86a5aa1d547a2ca81e118e34/update_ebuilds#L60-L61). More information in here: https://github.com/kinvolk/coreos-overlay#updating

**Comment by tormath1** [comment]
@sayanchowdhury @jepio CI is :large_blue_circle: with `1.9.3` :balloon:

**Comment by jepio** [comment]
Awesome! Go ahead and merge
________________________________

**Pull request merged**
